### ISSUE TITLE
Question about apply scales for fc2

### ISSUE THREAD

**Issue by Taka152** [mit-han-lab/llm-awq#12]
Thanks for your guys' great work from smoothquant to awq.
I have a question about this line.
https://github.com/mit-han-lab/llm-awq/blob/06e299ba0b27de0b9f34fdb0e8c8f4848095f612/awq/quantize/auto_scale.py#L173-L177
why could we transfer the scale from fc2 to fc1? there is a nonlinear activation function between two fc.

**Comment by tonylins** [comment]
Hi, this is a good question. For activation functions like ReLU (used by OPT), it is possible to directly multiply the scaling. 
For GLU activation function (y = x * \sigma(x), used by LLaMA), we can also fuse it since there is a x in the input (generated by Linear layer).
For activation functions like GeLU, it is not possible to fuse it into previous linear layers. But we can add a separate scaling node and fuse it into GeLU with a kernel implementation. We are actively working on that and will extend the support to BLOOM once the kernel fusion is done.

**Comment by Taka152** [comment]
Got it, thanks

**Comment by fxmarty-amd** [comment]
@tonylins but `sigmax(s * x) != s * sigmax(x)`, so fusing the scale with preceding layer is not correct.
