### ISSUE TITLE
Can not load pre-computed AWQ results for Bloom7b

### ISSUE THREAD

**Issue by moonlightian** [mit-han-lab/llm-awq#16]
Thanks for your support for Bloom updated today! I tried with Bloom-7b but failed.
After performing AWQ search and save search results , I tried to reload and evaluate with cmd
'python -m awq.entry --model_path /tmp/bloom_orig_0608/ --w_bit 4 --q_group_size 128 --run_awq --load_awq awq_cache/bloom-7b-w4-g128.pt --tasks wikitext --q_backend fake'
but raise NotImplementedError with awq.quantize.qmodule.ScaledActivation like:
![image](https://github.com/mit-han-lab/llm-awq/assets/49636631/0e169a07-8c8b-4079-a2a3-2b801c483f08)

**Comment by Sakits** [comment]
Hi @moonlightian , thank you for raising this issue!

The issue occurs due to running AWQ search (--run_awq) while also loading the AWQ checkpoint (--load_awq). Please remove the --run_awq flag while keeping the --load_awq one. We've made some updates to prevent this issue from happening. Please try again with these change!

Thanks again for your interest in AWQ!
