### ISSUE TITLE
Support for MPT models

### ISSUE THREAD

**Issue by casperbh96** [mit-han-lab/llm-awq#5]
Hi @kentang-mit, great work and research!

I would like to suggest implementing the MPT foundational models for AWQ.

MPT obstacles:
- uses ALiBi
- uses Triton with FlashAttention

What are your thoughts on supporting other architectures and foundational open-source models?

**Comment by kentang-mit** [comment]
Hi @casperbh96,

Thank you for your interest! I think AWQ is a general technique that can potentially work for many different models. The two things you mentioned in the issue (ALiBi position embedding and flashattention) should be okay for AWQ because they are related to the no-parametric MHSA module. We will definitely have a look at MPT and other recent methods (e.g. Falcon) to see if the method and kernel still works. 

Best,
Haotian

**Comment by abhinavkulkarni** [comment]
@casperbh96: Support for MPT models has been added in `dev/more_models` branch.
